services:
  # Full-Stack Web Service running FastAPI & React (Docker)
  - type: web
    name: url-fishing
    runtime: docker
    plan: free
    dockerContext: .
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: PORT
        value: 8000
